FROM maven:3.8.5-openjdk-17 AS development

COPY notificationservice /app/notificationservice
WORKDIR /app/notificationservice
EXPOSE 8080

CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]