FROM maven:3.8.5-openjdk-17-slim AS development
RUN apt-get update && apt-get install -y wget

COPY notificationservice /app/notificationservice
WORKDIR /app/notificationservice
EXPOSE 8080

CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]