FROM maven:3.8.5-openjdk-17 AS development

COPY AnimalsDataCore/pom.xml /app/AnimalsDataCore/pom.xml
WORKDIR /app/AnimalsDataCore
RUN mvn dependency:go-offline -B
COPY AnimalsDataCore/src /app/AnimalsDataCore/src
RUN mvn clean install -DskipTests

COPY actionservice /app/actionservice
WORKDIR /app/actionservice
EXPOSE 8080

CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]